// Generated by EmberScript 0.0.14
var set$ = Ember.set;
set$(Enterprise, 'ApplicationController', Ember.ArrayController.extend({
  savedTransition: null,
  login: function () {
    return true;
  },
  logout: function () {
    return false;
  }
}));