// Generated by EmberScript 0.0.14
var set$ = Ember.set;
var get$ = Ember.get;
set$(Enterprise, 'AssodirSerializer', get$(Enterprise, 'ApplicationSerializer').extend({
  extractArray: function (store, type, payload) {
    var assodirs;
    assodirs = get$(payload, 'assodirs');
    assodirs.forEach(function (json) {
      console.log(json);
      return set$(json, 'id', get$(json, 'name'));
    });
    return this._super(store, type, { assodir: assodirs });
  }
}));