// Generated by EmberScript 0.0.14
var set$ = Ember.set;
var get$ = Ember.get;
set$(Enterprise, 'OrgSerializer', get$(DS, 'JSONSerializer').extend({
  extractArray: function (store, type, payload) {
    return payload.map(function (json) {
      return this.extractSingle(store, type, json);
    }, this);
  }
}));