// Generated by EmberScript 0.0.14
var set$ = Ember.set;
var get$ = Ember.get;
set$(Enterprise, 'ActListRoute', Ember.Route.extend({
  model: function () {
    return get$(this, 'store').find('actList');
  }
}));