// Generated by EmberScript 0.0.14
var set$ = Ember.set;
var get$ = Ember.get;
set$(Enterprise, 'ActShowRoute', Ember.Route.extend({
  model: function (params) {
    console.log(get$(params, 'act_id'));
    return get$(this, 'store').find('activity', get$(params, 'act_id'));
  }
}));