// Generated by EmberScript 0.0.14
var set$ = Ember.set;
var get$ = Ember.get;
set$(Enterprise, 'ActShowRoute', get$(Em, 'Route').extend({
  model: function (params) {
    var act_id, fields, session;
    act_id = get$(params, 'act_id');
    session = localStorage.getItem('xiaoxiao:session');
    fields = [
      'name',
      'stage',
      'location',
      'category',
      'description',
      'begin',
      'end',
      'numberOfPeople',
      'numberOfPreservedSeats',
      'organizationName',
      'organizationId',
      'signingUpFields',
      'poster',
      'images',
      'attachments',
      'targets',
      'budgets'
    ];
    return get$(Em, '$').ajax({ url: '/api/event/' + act_id + '/load?session=' + session + '&fields=' + fields.join(',') }).then(function (this$) {
      return function (data) {
        if (get$(data, 'status') === 'OK') {
          console.log(data);
          return get$(this$, 'store').push('activity', get$(data, 'static'));
        } else if (get$(data, 'status') === 'Permission Denied') {
          get$(Em, 'RSVP').reject('Permission Denied');
          history.go(-1);
          return Notifier.error('\u5BF9\u4E0D\u8D77\uFF0C\u4F60\u6CA1\u6709\u6743\u9650\u67E5\u770B\u8BE5\u6D3B\u52A8');
        }
      };
    }(this));
  }
}));