// Generated by EmberScript 0.0.14
var set$ = Ember.set;
set$(Enterpriseedition, 'ApplicationRoute', Ember.Route.extend({
  model: function () {
    return [
      'red',
      'yellow',
      'blue'
    ];
  }
}));