// Generated by EmberScript 0.0.14
var set$ = Ember.set;
var get$ = Ember.get;
set$(Enterprise, 'AuthenticatedRoute', Ember.Route.extend({
  beforeModel: function (transition) {
    var applicationController, userSession;
    applicationController = this.controllerFor('application');
    userSession = localStorage.getItem('xiaoxiao:session');
    if (userSession && userSession !== 'null') {
      return this.controllerFor('application').login();
    } else {
      applicationController.set('savedTransition', transition);
      return this.transitionTo('login');
    }
  }
}));