// Generated by EmberScript 0.0.14
var set$ = Ember.set;
var get$ = Ember.get;
set$(Enterprise, 'HomeRoute', get$(Em, 'Route').extend({
  model: function () {
    return get$(Enterprise, 'Auth');
  }
}));