// Generated by EmberScript 0.0.14
var set$ = Ember.set;
var get$ = Ember.get;
set$(Enterprise, 'OrgShowRoute', Ember.Route.extend({
  model: function (params) {
    return get$(this, 'store').find('org', get$(params, 'org_id'));
  }
}));