// Generated by EmberScript 0.0.14
var set$ = Ember.set;
var get$ = Ember.get;
set$(Enterprise, 'OrgShowRoute', Ember.Route.extend({
  model: function (params) {
    var fields, session;
    session = localStorage.getItem('xiaoxiao:session');
    fields = [
      'organizationInfo.id',
      'organizationInfo.name',
      'organizationInfo.parent',
      'organizationInfo.email',
      'organizationInfo.contact',
      'organizationInfo.description',
      'extendedOrganizationInfo.type',
      'extendedOrganizationInfo.credit',
      'dynamic.numberOfMembers',
      'dynamic.numberOfFollowers',
      'dynamic.numberOfEvents',
      'dynamic.roleType'
    ];
    return get$(Em, '$').ajax({ url: '/api/org/' + get$(params, 'org_id') + '/info?session=' + session + '&fields=' + fields.join(',') }).then(function (data) {
      return console.log(data);
    });
  }
}));