// Generated by EmberScript 0.0.14
var set$ = Ember.set;
var get$ = Ember.get;
set$(Enterprise, 'OrgSearchRoute', Ember.Route.extend({
  model: function (params) {
    var session;
    session = localStorage.getItem('xiaoxiao:session');
    return get$(Em, '$').ajax({
      url: '/api/assodir/search?session=' + session + '&name&skip=0&limit=10',
      dataType: 'json'
    }).then(function (this$) {
      return function (payload) {
        var assodirData, assodirSerializer, firstAssodir;
        if (get$(payload, 'status') === 'OK') {
          firstAssodir = get$(params, 'assodir_id');
          assodirSerializer = get$(this$, 'store').serializerFor('assodir');
          assodirData = assodirSerializer.extractArray(this$.get('store'), get$(Enterprise, 'Assodir'), payload);
          get$(this$, 'store').pushMany('assodir', assodirData);
          return get$(Em, '$').ajax({
            url: '/api/assodir/' + encodeURI(firstAssodir) + '/load?session=' + session,
            dataType: 'json'
          }).then(function (this$1) {
            return function (payload) {
              var organizationsData;
              organizationsData = get$(payload, 'organizations');
              organizationsData.map(function (json) {
                return set$(json, 'assodir', firstAssodir);
              });
              get$(this$1, 'store').pushMany('org', organizationsData);
              assodirData = get$(this$1, 'store').all('assodir');
              console.log(organizationsData);
              return {
                organizations: organizationsData,
                assodirs: assodirData
              };
            };
          }(this$));
        } else {
          return get$(Em, 'RSVP').reject('Service Error');
        }
      };
    }(this));
  },
  actions: {
    chDir: function (name) {
      return console.log(name);
    }
  }
}));