// Generated by EmberScript 0.0.14
var set$ = Ember.set;
var get$ = Ember.get;
set$(Enterprise, 'SettingProfileRoute', get$(Em, 'Route').extend({
  model: function () {
    return get$(Enterprise, 'Auth').get('ent');
  },
  setupController: function (controller, model) {
    return controller.set('model', model);
  }
}));