// Generated by EmberScript 0.0.14
var set$ = Ember.set;
var get$ = Ember.get;
set$(Enterprise, 'SponsorListRoute', Ember.Route.extend({
  model: function () {
    var session;
    session = localStorage.getItem('xiaoxiao:session');
    return get$(Em, '$').ajax({ url: '/api/sponsor/list_sponsor_requests?session=' + session + '&skip=0&limit=10' }).then(function (this$) {
      return function (payload) {
        var data;
        console.log(payload);
        if (get$(payload, 'status') === 'OK') {
          data = get$(payload, 'sponsorRequests').map(function (json) {
            set$(get$(json, 'sponsor'), 'timeOfRequest', get$(get$(get$(json, 'sponsor'), 'timeOfRequest'), '$date'));
            return get$(json, 'sponsor');
          });
          return get$(this$, 'store').pushMany('sponsorList', data);
        }
      };
    }(this));
  }
}));