// Generated by EmberScript 0.0.14
var set$ = Ember.set;
var get$ = Ember.get;
set$(Enterprise, 'SponsorShowRoute', get$(Em, 'Route').extend({
  model: function (params) {
    var fields, session, sponsorId;
    session = localStorage.getItem('xiaoxiao:session');
    sponsorId = get$(params, 'sponsor_id');
    fields = [
      'demanding',
      'title',
      'providing',
      'publicity',
      'praiserfund',
      'money'
    ];
    return get$(Em, '$').ajax({ url: '/api/sponsor/sponsor_request/' + sponsorId + '/load?session=' + session + '&fields=' + fields.join(',') }).then(function (this$) {
      return function (payload) {
        var eventIds, requestAttachmentIds;
        if (get$(payload, 'status') === 'OK') {
          this$.get('store').pushMany('activity', get$(payload, 'events'));
          get$(get$(payload, 'sponsor'), 'requestAttachment').map(function (json) {
            set$(json, 'id', get$(json, 'file'));
            return json;
          });
          this$.get('store').pushMany('requestAttachment', get$(get$(payload, 'sponsor'), 'requestAttachment'));
          set$(get$(payload, 'sponsor'), 'events', get$(payload, 'events'));
          eventIds = get$(get$(payload, 'sponsor'), 'events').mapProperty('id');
          requestAttachmentIds = get$(get$(payload, 'sponsor'), 'requestAttachment').mapProperty('id');
          set$(get$(payload, 'sponsor'), 'events', eventIds);
          set$(get$(payload, 'sponsor'), 'requestAttachment', requestAttachmentIds);
          return this$.get('store').push('sponsor', get$(payload, 'sponsor'));
        }
      };
    }(this));
  }
}));