// Generated by EmberScript 0.0.14
var set$ = Ember.set;
var get$ = Ember.get;
Ember.Handlebars.helper('bg', function (value) {
  return 'background-image:url(' + value + '),url(images/default/30.jpg);';
});