// Generated by EmberScript 0.0.14
var set$ = Ember.set;
var get$ = Ember.get;
set$(Enterprise, 'Activity', get$(DS, 'Model').extend({
  name: DS.attr('string'),
  stage: DS.attr('string'),
  location: DS.attr('string'),
  category: DS.attr('string'),
  description: DS.attr('string'),
  begin: DS.attr('date'),
  end: DS.attr('date'),
  numberOfPeople: DS.attr('number'),
  numberOfPreservedSeats: DS.attr('number'),
  organizationName: DS.attr('string'),
  organizationId: DS.attr('number'),
  signingUpFields: DS.attr(),
  poster: DS.attr(),
  images: DS.attr(),
  attachments: DS.attr(),
  targets: DS.attr(),
  budgets: DS.attr()
}));