// Generated by EmberScript 0.0.14
var set$ = Ember.set;
var get$ = Ember.get;
set$(Enterprise, 'ActList', get$(DS, 'Model').extend({
  stage: DS.attr('string'),
  name: DS.attr('string'),
  location: DS.attr('string'),
  category: DS.attr('string'),
  description: DS.attr('string'),
  begin: DS.attr('date'),
  end: DS.attr('date'),
  numberOfPraisers: DS.attr('number'),
  posterSrc: Ember.computed(function () {
    return '/api/event/' + get$(this, 'id') + '/poster/load';
  }).property('id')
}));