// Generated by EmberScript 0.0.14
var set$ = Ember.set;
var get$ = Ember.get;
set$(Enterprise, 'Activity', get$(DS, 'Model').extend({
  stage: DS.attr('string'),
  name: DS.attr('string'),
  location: DS.attr('string'),
  category: DS.attr('string'),
  description: DS.attr('string'),
  begin: DS.attr('date'),
  end: DS.attr('date'),
  numberOfPraisers: DS.attr('number'),
  posterSrc: Ember.computed(function () {
    return '/api/event/' + get$(this, 'id') + '/poster/load';
  }).property('id')
}));
set$(get$(Enterprise, 'Activity'), 'FIXTURES', [
  {
    stage: 'drafting',
    name: '\u5475\u5475\u5475\u5475\u5475',
    location: '\u770B\u56FE\u7247',
    category: '\u8BB2\u5EA7',
    description: '\u5566\u5566\u5566\u5566\u5566',
    begin: '2014-08-01T18:15:00.000Z',
    end: '2014-08-12T09:55:00.000Z',
    id: '53dcca0ba80654311c798252',
    numberOfPraisers: 0
  },
  {
    stage: 'drafting',
    name: '\u65B0\u7684\u6D3B\u52A8',
    location: '\u590D\u65E6\u5927\u5B66',
    category: '\u8BB2\u5EA7',
    description: '\u5566\u5566\u5566\u5566',
    begin: '2014-08-07T17:10:00.000Z',
    end: '2014-08-08T18:15:00.000Z',
    id: '53e367693866cb817ce7881a',
    numberOfPraisers: 0
  }
]);