// Generated by EmberScript 0.0.14
var set$ = Ember.set;
var get$ = Ember.get;
set$(Enterprise, 'Org', get$(DS, 'Model').extend({
  contact: DS.attr('number'),
  name: DS.attr('string'),
  roleType: DS.attr('string'),
  user: DS.belongsTo('user'),
  orgLogo: Ember.computed(function () {
    return '/api/org/' + get$(this, 'id') + '/logo';
  }).property('id')
}));