// Generated by EmberScript 0.0.14
var set$ = Ember.set;
var get$ = Ember.get;
set$(Enterprise, 'RequestAttachment', get$(DS, 'Model').extend({
  file: DS.attr('string'),
  filename: DS.attr('string')
}));