// Generated by EmberScript 0.0.14
var set$ = Ember.set;
var get$ = Ember.get;
set$(Enterprise, 'SponsorList', get$(DS, 'Model').extend({
  demanding: DS.attr('string'),
  owner: DS.attr('number'),
  providing: DS.attr('string'),
  publicity: DS.attr('boolean'),
  timeOfRequest: DS.attr('date'),
  title: DS.attr('string'),
  orgLogo: Ember.computed(function () {
    return '/api/org/' + get$(this, 'owner') + '/logo';
  }).property('owner')
}));